#export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
export QT_QPA_PLATFORMTHEME="qt5ct"
export QT_QPA_PLATFORMTHEME="gtk2"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
. "$HOME/.cargo/env"
export BROWSER=/usr/bin/brave
export TERM=/usr/bin/kitty
export EDITOR=/usr/bin/emacs
export SHELL=/usr/bin/bash
