#!/bin/sh
while read file
do
        case "$1" in
        "C-d")
                mv "$file" ~/.trash ;;
        "C-r")
                convert -rotate 90 "$file" "$file" ;;
        "C-c")
                echo -n "$file" | xclip -selection clipboard ;;
        "C-w")
                feh --bg-fill $file && cp $file ~/.config/background-image ;;
        "C-p")
                wal -n -q -i "$file" && cp $file ~/.config/color-scheme-image ;;
        esac
done
