theme = "modern"
icons = "awesome"

[[block]]
block = "cpu"
interval = 1

# [[block]]
# block = "custom"
# command = ''' acpi -t | cut -d " " -f 4 '''
# interval = 1
[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "docker"
interval = 2
format = "{running}/{total}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0


[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid}"
interval = 5
use_bits = false

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15
