theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "music"
buttons = ["play", "next"]
interface_name_exclude = [".*kdeconnect.*", "mpd"]


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"
[block.theme_overrides]
idle_bg = "#666666"
idle_fg = "#ffffff"

[[block]]
block = "cpu"
interval = 1
[block.theme_overrides]
idle_bg = "#444444"
idle_fg = "#ffffff"

[[block]]
block = "load"
interval = 1
format = "{1m}"
[block.theme_overrides]
idle_bg = "#222222"
idle_fg = "#ffffff"

[[block]]
block = "nvidia_gpu"
label = "GPU"
show_temperature = false
show_memory = false
show_clocks = false
interval = 1
[block.theme_overrides]
idle_bg = "#0e3801"
idle_fg = "#ffffff"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
[block.theme_overrides]
idle_fg = "#ffffff"

[[block]]
block = "net"
device = "wlp2s0"
format = "{ssid} {signal_strength} {ip}"
interval = 5
[block.theme_overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[[block]]
block = "sound"
max_vol = 100
[block.theme_overrides]
idle_bg = "#561250"
idle_fg = "#ffffff"

[[block]]
block = "time"
interval = 60
[block.theme_overrides]
idle_bg = "#185612"
idle_fg = "#ffffff"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

