add_newline = false # disable newline between prompts
# format = """$directory\n$character"""
format = """$directory\n$character"""
right_format = """$all"""

[directory]
truncation_length = 1
# truncation_symbol = '../'
