#!/bin/bash
#
export QCOW2_TO_MOUNT="$1"
export MOUNT_POINT="/tmp/$IMAGE_TO_MOUNT"

qemu-nbd --connect=/dev/nbd0 "$QCOW2_TO_MOUNT"
fdisk /dev/nbd0 -l
mount /dev/nbd0p1 "$MOUNT_POINT"
cd "$MOUNT_POINT" || exit
